version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:12.18.3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install Codecov
          command: npm install codecov

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found.
          - v1-dependencies-

      - run: npm install
      - run:
          name: Build component
          command: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run tests
          command: npm test -- --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/

      - run:
          name: Upload coverage report
          command: npx codecov

      - store_test_results:
          path: ./reports/junit/

      - store_artifacts:
          path: ./reports/junit

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2

  test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
